  Running command git clone --filter=blob:none --quiet https://github.com/IBM/graph2tac.git /tmp/pip-req-build-s97p25bu
  Running command git rev-parse -q --verify 'sha^0d2b9f8f466744d86962a9532a5fd485a938eca5'
  Running command git fetch -q https://github.com/IBM/graph2tac.git 0d2b9f8f466744d86962a9532a5fd485a938eca5
  Running command git checkout -q 0d2b9f8f466744d86962a9532a5fd485a938eca5
  Running command git clone --filter=blob:none --quiet 'https://****@github.com/coq-tactician/coq-tactician-reinforce' /tmp/pip-install-x7ply25a/pytact_bccccb1cc3eb49edaa3b06bf7865e03e
  Running command git submodule update --init --recursive -q

[notice] A new release of pip available: 22.2.1 -> 22.3.1
[notice] To update, run: pip install --upgrade pip
[ERROR] Failed to get extra source "model.tar.gz" of coq-graph2tac.~dev: http/64.71.146.254:8000/SFyud_C5TmEq7AwnK9jaLsfTFMzgBl54cQ0pl2FJB-x9o2Hk24F4jO_W75RqGdOJ/weights/2023-01-23_B_v14_ministdlib_epoch100.41f9650b225b61c9164c888ac8a05113.tar.gz

#=== ERROR while fetching sources for coq-graph2tac.~dev ======================#
OpamSolution.Fetch_fail("http/64.71.146.254:8000/SFyud_C5TmEq7AwnK9jaLsfTFMzgBl54cQ0pl2FJB-x9o2Hk24F4jO_W75RqGdOJ/weights/2023-01-23_B_v14_ministdlib_epoch100.41f9650b225b61c9164c888ac8a05113.tar.gz")
