File "./theories/Programming/Show.v", line 64, characters 2-37:
Warning: Declaring a scope implicitly is deprecated; use in advance an
explicit "Declare Scope show_scope.". [undeclared-scope,deprecated]
File "./affine_classiques.v", line 105, characters 0-41:
Error: Variable C should be bound to a tactic.

WARNING:tensorflow:5 out of the last 39 calls to <function ModelWrapper.get_predict_fn.<locals>.pred_fn at 0x14f2a1eb11b0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:5 out of the last 39 calls to <function ModelWrapper.get_predict_fn.<locals>.pred_fn at 0x14f2a1eb11b0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Traceback (most recent call last):
  File "/tmp/tactician.tmp.mrCiwu/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.mrCiwu/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.mrCiwu/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.mrCiwu/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.mrCiwu/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.mrCiwu/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.mrCiwu/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.mrCiwu/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.mrCiwu/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
