  Running command git clone --filter=blob:none --quiet https://github.com/IBM/graph2tac.git@ /tmp/pip-req-build-pz7bbh02
  fatal: unable to access 'https://github.com/IBM/graph2tac.git@/': The requested URL returned error: 400
  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet https://github.com/IBM/graph2tac.git@ /tmp/pip-req-build-pz7bbh02 did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/IBM/graph2tac.git@ /tmp/pip-req-build-pz7bbh02 did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: pip install --upgrade pip
