  Running command git clone --filter=blob:none --quiet https://github.com/IBM/graph2tac/commit/2c5b88cb2726301fa054cfda4d1730c7d1e3dc3f /tmp/pip-req-build-r7ffy9e2
  remote: Not Found
  fatal: repository 'https://github.com/IBM/graph2tac/commit/2c5b88cb2726301fa054cfda4d1730c7d1e3dc3f/' not found
  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet https://github.com/IBM/graph2tac/commit/2c5b88cb2726301fa054cfda4d1730c7d1e3dc3f /tmp/pip-req-build-r7ffy9e2 did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/IBM/graph2tac/commit/2c5b88cb2726301fa054cfda4d1730c7d1e3dc3f /tmp/pip-req-build-r7ffy9e2 did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: pip install --upgrade pip
