File "./theories/Init/Tactics.v", line 189, characters 0-45:
Warning:
now idtac((TacAlias Coq.Init.Tactics.now_#_62200C10 ((TacThen (TacArg (CAst (Reference (CAst t)))) (TacArg (CAst (TacCall Coq.Init.Tactics.easy (CAst Located)))))) (CAst (Tacexp (TacId)))))
File "./theories/Init/Tactics.v", line 189, characters 0-45:
Warning:
now idtac((TacAlias Coq.Init.Tactics.now_#_62200C10 ((TacThen (TacArg (CAst (Reference (CAst t)))) (TacArg (CAst (TacCall Coq.Init.Tactics.easy (CAst Located)))))) (CAst (Tacexp (TacId)))))
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/lscratch/blaaulas/neural-bib/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/lscratch/blaaulas/neural-bib/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
File "./theories/Wellfounded/Lexicographic_Product.v", line 53, characters 6-32:
Warning:
Tactician found a bug in it's tactical decomposition. Please report.
injection H3 as
[=-> H3]
injection H3 as _tmp_tactician0 H3;
 (intropattern subst -> _tmp_tactician0; idtac)

