Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias".     sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main

    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
File "./theories/Data/Fin.v", line 27, characters 2-22:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/SigT.v", line 17, characters 2-31:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Tactics/EqDep.v", line 13, characters 4-11:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Fin.v", line 38, characters 2-9:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/SigT.v", line 23, characters 2-147:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Nat.v", line 30, characters 2-21:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
File "./theories/Tactics/EqDep.v", line 18, characters 4-29:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/SigT.v", line 40, characters 7-19:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Tactics/EqDep.v", line 25, characters 4-11:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Nat.v", line 35, characters 2-21:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Fin.v", line 72, characters 0-29:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
File "./theories/Core/Decision.v", line 19, characters 2-11:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Nat.v", line 40, characters 2-21:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Fin.v", line 98, characters 2-14:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Nat.v", line 45, characters 2-21:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
File "./theories/Data/Nat.v", line 51, characters 2-21:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
File "./theories/Data/Nat.v", line 60, characters 2-40:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
File "./theories/Data/Nat.v", line 70, characters 2-40:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
File "./theories/Data/Nat.v", line 87, characters 0-29:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
File "./theories/Programming/Extras.v", line 37, characters 2-24:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Programming/Extras.v", line 44, characters 2-24:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
File "./theories/Data/HList.v", line 20, characters 2-21:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
File "./theories/Data/List.v", line 21, characters 4-8:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
File "./theories/Data/HList.v", line 27, characters 2-21:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
File "./theories/Data/Map/FMapAList.v", line 53, characters 4-27:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/List.v", line 36, characters 2-22:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 71, characters 4-11:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
File "./theories/Generic/DerivingData.v", line 31, characters 2-8:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Z.v", line 24, characters 2-21:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Map/FMapPositive.v", line 94, characters 4-152:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/List.v", line 46, characters 2-8:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 87, characters 4-37:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
File "./theories/Data/Map/FMapAList.v", line 82, characters 6-31:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Generic/DerivingData.v", line 39, characters 2-8:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Z.v", line 30, characters 2-21:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
File "./theories/Data/List.v", line 76, characters 2-22:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Map/FMapAList.v", line 116, characters 6-49:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Z.v", line 38, characters 2-21:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 113, characters 4-16:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/SumN.v", line 75, characters 2-35:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/List.v", line 84, characters 7-13:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 131, characters 6-10:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/SumN.v", line 81, characters 2-21:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Z.v", line 46, characters 2-21:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 137, characters 6-10:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/SumN.v", line 97, characters 2-15:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Z.v", line 54, characters 2-21:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 145, characters 6-10:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/List.v", line 92, characters 2-8:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Generic/Ind.v", line 153, characters 0-582:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Map/FMapAList.v", line 127, characters 6-18:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/List.v", line 142, characters 4-16:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/SumN.v", line 125, characters 2-13:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 177, characters 6-12:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Map/FMapAList.v", line 133, characters 6-55:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Vector.v", line 39, characters 4-21:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 198, characters 6-12:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/List.v", line 186, characters 4-106:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/SumN.v", line 131, characters 2-25:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Vector.v", line 58, characters 4-16:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Member.v", line 41, characters 4-21:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Map/FMapAList.v", line 144, characters 6-38:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Tuple.v", line 28, characters 2-14:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Vector.v", line 69, characters 4-16:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Member.v", line 57, characters 4-16:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/List.v", line 196, characters 0-38:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 223, characters 2-12:
Warning: Tactic could not be properly discharged: refine
(fun H' =>
 match
   H' in (@equiv_hlist ls X Y)
   return
     (match ls return (hlist ls -> hlist ls -> Prop) with
      | nil => fun _ _ : hlist nil => True
      | l :: ls =>
          fun X Y : hlist (l :: ls) =>
          forall Z x xs,
          eqv (hlist_hd Z) (hlist_hd X) ->
          equiv_hlist xs (hlist_tl X) ->
          (forall z : hlist ls,
           equiv_hlist (hlist_tl X) z -> equiv_hlist (hlist_tl Z) z) ->
          equiv_hlist Z Y
      end X Y)
 with
 | hlist_eqv_nil => I
 | @hlist_eqv_cons l ls x y h1 h2 pf pf' => _
 end (Hcons x h1) x _ H H0 IHequiv_hlist)
File "./theories/Data/HList.v", line 227, characters 4-47:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Member.v", line 67, characters 4-24:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/String.v", line 57, characters 2-122:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/List.v", line 201, characters 0-29:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 233, characters 4-47:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Tuple.v", line 39, characters 2-14:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Vector.v", line 164, characters 4-16:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/List.v", line 206, characters 0-29:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 241, characters 4-11:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Member.v", line 109, characters 2-32:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/List.v", line 211, characters 0-28:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 268, characters 4-31:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Member.v", line 121, characters 4-15:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Map/FMapPositive.v", line 103, characters 4-152:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Map/FMapAList.v", line 165, characters 6-49:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/List.v", line 218, characters 0-38:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Map/FMapAList.v", line 173, characters 6-38:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/List.v", line 225, characters 0-29:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 394, characters 4-16:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Member.v", line 135, characters 4-29:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/List.v", line 232, characters 0-29:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 404, characters 4-23:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Map/FMapAList.v", line 181, characters 6-26:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 446, characters 4-31:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Map/FMapAList.v", line 191, characters 6-26:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/String.v", line 68, characters 2-43:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/String.v", line 73, characters 2-52:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Map/FMapAList.v", line 202, characters 6-143:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/String.v", line 94, characters 4-35:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 461, characters 6-25:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/String.v", line 108, characters 4-35:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/String.v", line 116, characters 0-26:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Map/FMapPositive.v", line 113, characters 4-94:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/String.v", line 121, characters 0-25:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/String.v", line 126, characters 0-25:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Map/FMapPositive.v", line 124, characters 4-28:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Map/FMapPositive.v", line 134, characters 4-25:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/String.v", line 131, characters 0-26:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Map/FMapPositive.v", line 144, characters 4-25:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/String.v", line 150, characters 4-16:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 487, characters 6-12:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Programming/Show.v", line 64, characters 2-37:
Warning: Declaring a scope implicitly is deprecated; use in advance an
explicit "Declare Scope show_scope.". [undeclared-scope,deprecated]
File "./theories/Data/HList.v", line 506, characters 6-40:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Programming/Show.v", line 178, characters 4-45:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 516, characters 6-34:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 528, characters 4-10:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 540, characters 4-10:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Map/FMapPositive.v", line 162, characters 4-25:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 554, characters 4-10:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 602, characters 4-48:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 619, characters 4-48:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Map/FMapPositive.v", line 181, characters 4-11:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 633, characters 4-18:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Map/FMapPositive.v", line 192, characters 4-59:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Map/FMapPositive.v", line 211, characters 4-16:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 655, characters 4-10:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 680, characters 4-10:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Map/FMapPositive.v", line 231, characters 2-63:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 697, characters 0-10:
Warning: Tactic could not be properly discharged: refine
(fun H' =>
 match
   H' in (@equiv_hlist _ ls X Y)
   return
     (match ls return (hlist ls -> hlist ls -> Prop) with
      | nil => fun _ _ : hlist nil => True
      | l :: ls =>
          fun X Y : hlist (l :: ls) =>
          forall Z x xs,
          eqv _ (hlist_hd Z) (hlist_hd X) ->
          equiv_hlist _ (hlist_tl X) ->
          (forall z : hlist ls, equiv_hlist _ z -> equiv_hlist _ z) ->
          equiv_hlist (l :: ls) Y
      end X Y)
 with
 | @hlist_eqv_nil _ => I
 | @hlist_eqv_cons _ l ls x y h1 h2 pf pf' => _
 end (Hcons x h1) x _ H H0 IHequiv_hlist)
File "./theories/Data/Map/FMapPositive.v", line 267, characters 4-59:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 723, characters 4-16:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Map/FMapPositive.v", line 277, characters 4-59:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 741, characters 4-33:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/ListFirstnSkipn.v", line 9, characters 2-52:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
File "./theories/Data/ListFirstnSkipn.v", line 18, characters 2-52:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 747, characters 4-23:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
File "./theories/Data/HList.v", line 757, characters 4-30:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
File "./theories/Data/HList.v", line 772, characters 2-8:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
File "./theories/Data/HList.v", line 794, characters 4-29:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 810, characters 4-39:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 817, characters 4-11:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 827, characters 2-9:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
File "./theories/Data/HList.v", line 833, characters 2-9:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Option.v", line 56, characters 9-15:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
File "./theories/Data/Option.v", line 59, characters 9-15:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 840, characters 2-9:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Option.v", line 65, characters 4-10:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
File "./theories/Data/HList.v", line 847, characters 2-15:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
File "./theories/Data/Option.v", line 72, characters 2-30:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 856, characters 2-41:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Option.v", line 78, characters 2-31:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Option.v", line 84, characters 2-31:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/ListFirstnSkipn.v", line 27, characters 2-47:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 863, characters 2-15:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Option.v", line 90, characters 2-31:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
File "./theories/Data/Option.v", line 96, characters 2-31:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Char.v", line 34, characters 2-19:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 875, characters 2-45:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Structures/EqDep.v", line 14, characters 4-11:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/ListFirstnSkipn.v", line 36, characters 2-22:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 924, characters 4-43:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Structures/EqDep.v", line 19, characters 4-39:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 932, characters 4-11:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Structures/EqDep.v", line 26, characters 4-11:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 953, characters 4-16:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/ListFirstnSkipn.v", line 43, characters 2-21:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Structures/EqDep.v", line 31, characters 4-11:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Char.v", line 47, characters 2-42:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Char.v", line 52, characters 2-51:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/ListFirstnSkipn.v", line 54, characters 2-52:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Structures/EqDep.v", line 44, characters 4-16:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 970, characters 2-33:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/ListFirstnSkipn.v", line 63, characters 2-52:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/HList.v", line 979, characters 2-33:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Positive.v", line 25, characters 2-21:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/PList.v", line 132, characters 4-22:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Pair.v", line 18, characters 9-13:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/ListFirstnSkipn.v", line 72, characters 2-22:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Positive.v", line 31, characters 2-29:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Pair.v", line 22, characters 9-13:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Pair.v", line 26, characters 9-13:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Positive.v", line 37, characters 2-29:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/PList.v", line 145, characters 4-22:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Positive.v", line 43, characters 2-29:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/ListFirstnSkipn.v", line 79, characters 2-52:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Pair.v", line 29, characters 2-42:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/PList.v", line 158, characters 4-45:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Positive.v", line 51, characters 2-21:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Pair.v", line 50, characters 4-8:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
File "./theories/Data/ListFirstnSkipn.v", line 88, characters 2-21:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Pair.v", line 82, characters 4-347:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
File "./theories/Data/PList.v", line 170, characters 4-46:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
File "./theories/Data/PList.v", line 178, characters 4-56:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Pair.v", line 111, characters 4-348:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/PList.v", line 185, characters 4-18:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/PList.v", line 195, characters 4-18:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
File "./theories/Data/Pair.v", line 122, characters 0-38:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/PList.v", line 261, characters 4-391:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
File "./theories/Data/Option.v", line 136, characters 2-6:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
File "./theories/Data/Option.v", line 158, characters 4-372:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
File "./theories/Data/Option.v", line 180, characters 2-14:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
File "./theories/Core/EquivDec.v", line 6, characters 2-9:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Sum.v", line 37, characters 4-393:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
File "./theories/Core/CmpDec.v", line 53, characters 4-16:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
File "./theories/Data/ListNth.v", line 14, characters 4-49:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
File "./theories/Data/Sum.v", line 73, characters 4-348:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Tactics/Reify.v", line 26, characters 2-69:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
File "./theories/Data/ListNth.v", line 24, characters 4-49:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Sum.v", line 84, characters 0-29:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/ListNth.v", line 33, characters 4-10:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Sum.v", line 88, characters 0-29:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/ListNth.v", line 39, characters 4-28:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Sum.v", line 92, characters 0-29:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Sum.v", line 96, characters 0-29:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/ListNth.v", line 46, characters 4-10:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/ListNth.v", line 54, characters 4-32:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/ListNth.v", line 63, characters 4-59:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Tactics/Parametric.v", line 15, characters 0-10:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
File "./theories/Tactics/Parametric.v", line 21, characters 0-10:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/ListNth.v", line 72, characters 4-50:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Tactics/Parametric.v", line 27, characters 0-39:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Tactics/Parametric.v", line 59, characters 0-19:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Tactics/Parametric.v", line 72, characters 4-23:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
File "./theories/Data/ListNth.v", line 86, characters 4-42:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Tactics/Parametric.v", line 77, characters 4-23:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
File "./theories/Programming/Le.v", line 16, characters 7-19:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
File "./theories/Tactics/Consider.v", line 24, characters 2-9:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/PPair.v", line 30, characters 4-10:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/PPair.v", line 58, characters 2-40:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Tactics/Consider.v", line 33, characters 2-9:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/PPair.v", line 84, characters 4-16:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Tactics/Consider.v", line 46, characters 2-181:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Tactics/Consider.v", line 53, characters 2-190:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Tactics/Consider.v", line 73, characters 4-52:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Tactics/Consider.v", line 78, characters 4-52:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Recur/Relation.v", line 13, characters 4-8:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Recur/Relation.v", line 27, characters 4-8:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Bool.v", line 14, characters 2-14:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Tactics/Consider.v", line 83, characters 4-39:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Tactics/Consider.v", line 99, characters 4-26:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Tactics/Parametric.v", line 104, characters 4-11:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Tactics/Parametric.v", line 134, characters 4-17:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
File "./theories/Programming/Eqv.v", line 45, characters 9-99:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
File "./theories/Data/Unit.v", line 9, characters 2-14:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
File "./theories/Data/Eq.v", line 18, characters 2-14:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
File "./theories/Data/Eq.v", line 56, characters 2-9:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
File "./theories/Data/Eq.v", line 64, characters 2-8:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
File "./theories/Data/Eq.v", line 74, characters 2-14:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
File "./theories/Data/Eq.v", line 89, characters 2-14:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Eq.v", line 95, characters 7-19:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Prop.v", line 6, characters 7-17:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Relations/TransitiveClosure.v", line 19, characters 4-16:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Tactics/BoolTac.v", line 10, characters 2-19:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Relations/TransitiveClosure.v", line 70, characters 4-10:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Relations/TransitiveClosure.v", line 93, characters 4-18:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Recur/GenRec.v", line 26, characters 4-39:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Prop.v", line 33, characters 7-17:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Relations/TransitiveClosure.v", line 102, characters 4-11:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Tactics/BoolTac.v", line 15, characters 2-19:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Relations/TransitiveClosure.v", line 106, characters 4-11:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Prop.v", line 36, characters 7-17:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Recur/GenRec.v", line 36, characters 4-24:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Prop.v", line 39, characters 7-17:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Relations/TransitiveClosure.v", line 121, characters 4-10:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Relations/TransitiveClosure.v", line 129, characters 4-10:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Prop.v", line 42, characters 7-17:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
File "./theories/Data/Prop.v", line 45, characters 7-17:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Relations/TransitiveClosure.v", line 141, characters 4-56:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Prop.v", line 50, characters 2-23:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
File "./theories/Data/Prop.v", line 58, characters 7-13:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
File "./theories/Data/Prop.v", line 61, characters 7-13:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Core/RelDec.v", line 25, characters 9-20:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Prop.v", line 65, characters 7-13:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Recur/Facts.v", line 6, characters 2-302:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Prop.v", line 74, characters 3-10:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
File "./theories/Core/RelDec.v", line 50, characters 9-60:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
File "./theories/Core/RelDec.v", line 62, characters 4-11:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Prop.v", line 81, characters 2-8:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Core/RelDec.v", line 68, characters 4-11:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
File "./theories/Data/Prop.v", line 91, characters 3-10:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Core/RelDec.v", line 77, characters 4-11:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Prop.v", line 98, characters 2-8:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Prop.v", line 103, characters 7-13:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
File "./theories/Data/Prop.v", line 12, characters 7-17:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Relations/TransitiveClosure.v", line 24, characters 4-10:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Prop.v", line 9, characters 7-17:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
File "./theories/Tactics/Consider.v", line 39, characters 2-183:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
File "./theories/Data/Prop.v", line 15, characters 7-17:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Eq.v", line 29, characters 2-14:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
File "./theories/Core/RelDec.v", line 44, characters 9-59:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
File "./theories/Data/Prop.v", line 18, characters 7-17:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
File "./theories/Relations/TransitiveClosure.v", line 36, characters 4-10:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Eq.v", line 41, characters 2-14:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./theories/Data/Prop.v", line 22, characters 7-17:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
File "./theories/Relations/TransitiveClosure.v", line 41, characters 4-10:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
File "./theories/Data/Prop.v", line 29, characters 7-24:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 363, in main
    tokenizer, model = load_eval_setup(tokenizer_location, model_location)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 187, in load_eval_setup
    model.load_state_dict(torch.load(model_location, map_location=torch.device('cpu')))
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd6/target-source/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomGPT2LMHeadModel:
	Unexpected key(s) in state_dict: "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias". 
File "./theories/Core/RelDec.v", line 106, characters 4-16:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
