Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/bin/text2tac-server", line 33, in <module>
    sys.exit(load_entry_point('text2tac==0.1.0', 'console_scripts', 'text2tac-server')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 306, in main
    with Server(addr, Handler) as server:
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 304, in __init__
    super().__init__(*kwargs)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 452, in __init__
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/bin/text2tac-server", line 33, in <module>
    sys.exit(load_entry_point('text2tac==0.1.0', 'console_scripts', 'text2tac-server')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 306, in main
    with Server(addr, Handler) as server:
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 304, in __init__
    super().__init__(*kwargs)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 452, in __init__
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/bin/text2tac-server", line 33, in <module>
    sys.exit(load_entry_point('text2tac==0.1.0', 'console_scripts', 'text2tac-server')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 306, in main
    with Server(addr, Handler) as server:
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 304, in __init__
    super().__init__(*kwargs)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 466, in server_bind
    self.server_bind()
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 466, in server_bind
    self.server_bind()
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
    self.socket.bind(self.server_address)
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied
PermissionError: [Errno 13] Permission denied
PermissionError: [Errno 13] Permission denied
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/bin/text2tac-server", line 33, in <module>
    sys.exit(load_entry_point('text2tac==0.1.0', 'console_scripts', 'text2tac-server')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 306, in main
    with Server(addr, Handler) as server:
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 304, in __init__
    super().__init__(*kwargs)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/bin/text2tac-server", line 33, in <module>
    sys.exit(load_entry_point('text2tac==0.1.0', 'console_scripts', 'text2tac-server')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 306, in main
    with Server(addr, Handler) as server:
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 304, in __init__
    super().__init__(*kwargs)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/bin/text2tac-server", line 33, in <module>
    sys.exit(load_entry_point('text2tac==0.1.0', 'console_scripts', 'text2tac-server')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 306, in main
    with Server(addr, Handler) as server:
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 304, in __init__
    super().__init__(*kwargs)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/bin/text2tac-server", line 33, in <module>
    sys.exit(load_entry_point('text2tac==0.1.0', 'console_scripts', 'text2tac-server')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 306, in main
    with Server(addr, Handler) as server:
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 304, in __init__
    super().__init__(*kwargs)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/bin/text2tac-server", line 33, in <module>
    sys.exit(load_entry_point('text2tac==0.1.0', 'console_scripts', 'text2tac-server')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 306, in main
    with Server(addr, Handler) as server:
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 304, in __init__
    super().__init__(*kwargs)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/bin/text2tac-server", line 33, in <module>
    sys.exit(load_entry_point('text2tac==0.1.0', 'console_scripts', 'text2tac-server')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 306, in main
    with Server(addr, Handler) as server:
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 304, in __init__
    super().__init__(*kwargs)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/bin/text2tac-server", line 33, in <module>
    sys.exit(load_entry_point('text2tac==0.1.0', 'console_scripts', 'text2tac-server')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 306, in main
    with Server(addr, Handler) as server:
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 304, in __init__
    super().__init__(*kwargs)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/bin/text2tac-server", line 33, in <module>
    sys.exit(load_entry_point('text2tac==0.1.0', 'console_scripts', 'text2tac-server')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 306, in main
    with Server(addr, Handler) as server:
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 304, in __init__
    super().__init__(*kwargs)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/bin/text2tac-server", line 33, in <module>
    sys.exit(load_entry_point('text2tac==0.1.0', 'console_scripts', 'text2tac-server')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 306, in main
    with Server(addr, Handler) as server:
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 304, in __init__
    super().__init__(*kwargs)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/bin/text2tac-server", line 33, in <module>
    sys.exit(load_entry_point('text2tac==0.1.0', 'console_scripts', 'text2tac-server')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 306, in main
    with Server(addr, Handler) as server:
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 304, in __init__
    super().__init__(*kwargs)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/bin/text2tac-server", line 33, in <module>
    sys.exit(load_entry_point('text2tac==0.1.0', 'console_scripts', 'text2tac-server')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 306, in main
    with Server(addr, Handler) as server:
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 304, in __init__
    super().__init__(*kwargs)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/bin/text2tac-server", line 33, in <module>
    sys.exit(load_entry_point('text2tac==0.1.0', 'console_scripts', 'text2tac-server')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 306, in main
    with Server(addr, Handler) as server:
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 304, in __init__
    super().__init__(*kwargs)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/bin/text2tac-server", line 33, in <module>
    sys.exit(load_entry_point('text2tac==0.1.0', 'console_scripts', 'text2tac-server')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 306, in main
    with Server(addr, Handler) as server:
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 304, in __init__
    super().__init__(*kwargs)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied
File "./NGroundTac.v", line 9, characters 7-20:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./NatSignTac.v", line 62, characters 0-34:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./Rex.v", line 9, characters 0-7:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./PolAux.v", line 197, characters 7-64:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./Natex.v", line 57, characters 0-9:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./NatAux.v", line 82, characters 0-43:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./RAux.v", line 58, characters 7-55:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
File "./RAux.v", line 103, characters 7-68:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
File "./ReplaceTest.v", line 253, characters 0-7:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
File "./ReplaceTest.v", line 303, characters 0-7:
Warning:
Benchmarking error: Anomaly
                    "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/bin/text2tac-server", line 33, in <module>
    sys.exit(load_entry_point('text2tac==0.1.0', 'console_scripts', 'text2tac-server')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 306, in main
    with Server(addr, Handler) as server:
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 304, in __init__
    super().__init__(*kwargs)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/bin/text2tac-server", line 33, in <module>
    sys.exit(load_entry_point('text2tac==0.1.0', 'console_scripts', 'text2tac-server')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 306, in main
    with Server(addr, Handler) as server:
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 304, in __init__
    super().__init__(*kwargs)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/bin/text2tac-server", line 33, in <module>
    sys.exit(load_entry_point('text2tac==0.1.0', 'console_scripts', 'text2tac-server')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 306, in main
    with Server(addr, Handler) as server:
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 304, in __init__
    super().__init__(*kwargs)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/bin/text2tac-server", line 33, in <module>
    sys.exit(load_entry_point('text2tac==0.1.0', 'console_scripts', 'text2tac-server')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 306, in main
    with Server(addr, Handler) as server:
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 304, in __init__
    super().__init__(*kwargs)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/bin/text2tac-server", line 33, in <module>
    sys.exit(load_entry_point('text2tac==0.1.0', 'console_scripts', 'text2tac-server')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 306, in main
    with Server(addr, Handler) as server:
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 304, in __init__
    super().__init__(*kwargs)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/bin/text2tac-server", line 33, in <module>
    sys.exit(load_entry_point('text2tac==0.1.0', 'console_scripts', 'text2tac-server')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 306, in main
    with Server(addr, Handler) as server:
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 304, in __init__
    super().__init__(*kwargs)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/bin/text2tac-server", line 33, in <module>
    sys.exit(load_entry_point('text2tac==0.1.0', 'console_scripts', 'text2tac-server')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 306, in main
    with Server(addr, Handler) as server:
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 304, in __init__
    super().__init__(*kwargs)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/bin/text2tac-server", line 33, in <module>
    sys.exit(load_entry_point('text2tac==0.1.0', 'console_scripts', 'text2tac-server')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 306, in main
    with Server(addr, Handler) as server:
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 304, in __init__
    super().__init__(*kwargs)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/bin/text2tac-server", line 33, in <module>
    sys.exit(load_entry_point('text2tac==0.1.0', 'console_scripts', 'text2tac-server')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 306, in main
    with Server(addr, Handler) as server:
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 304, in __init__
    super().__init__(*kwargs)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/bin/text2tac-server", line 33, in <module>
    sys.exit(load_entry_point('text2tac==0.1.0', 'console_scripts', 'text2tac-server')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 306, in main
    with Server(addr, Handler) as server:
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 304, in __init__
    super().__init__(*kwargs)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/bin/text2tac-server", line 33, in <module>
    sys.exit(load_entry_point('text2tac==0.1.0', 'console_scripts', 'text2tac-server')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 306, in main
    with Server(addr, Handler) as server:
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 304, in __init__
    super().__init__(*kwargs)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/bin/text2tac-server", line 33, in <module>
    sys.exit(load_entry_point('text2tac==0.1.0', 'console_scripts', 'text2tac-server')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 306, in main
    with Server(addr, Handler) as server:
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 304, in __init__
    super().__init__(*kwargs)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/bin/text2tac-server", line 33, in <module>
    sys.exit(load_entry_point('text2tac==0.1.0', 'console_scripts', 'text2tac-server')())
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 306, in main
    with Server(addr, Handler) as server:
  File "/raid/scratch/piepejel/projects/coq-bench-15may/bd/target-source/venv/lib/python3.10/site-packages/text2tac/transformer/predict_server.py", line 304, in __init__
    super().__init__(*kwargs)
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/raid/scratch/piepejel/projects/coq-bench-15may/venv-benchmark/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied
